# Generated by Django 4.2.6 on 2023-10-30 17:55

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metatag', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='QueryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('services', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SureveyQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('total_score', models.IntegerField(blank=True, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
                ('quest_head_1', models.CharField(blank=True, default='Does business have missed-call text-back in place?', max_length=255, null=True)),
                ('yes_1', models.BooleanField(default=False)),
                ('no_1', models.BooleanField(default=False)),
                ('quest_head_2', models.CharField(blank=True, default='Does website have a text-enabled phone number?', max_length=255, null=True)),
                ('yes_2', models.BooleanField(default=False)),
                ('no_2', models.BooleanField(default=False)),
                ('quest_head_3', models.CharField(blank=True, default='Does website have an SMS chat widget?', max_length=255, null=True)),
                ('yes_3', models.BooleanField(default=False)),
                ('no_3', models.BooleanField(default=False)),
                ('quest_head_4', models.CharField(blank=True, default='Is Google Business Chat enabled?', max_length=255, null=True)),
                ('yes_4', models.BooleanField(default=False)),
                ('no_4', models.BooleanField(default=False)),
                ('quest_head_5', models.CharField(blank=True, default='Are popular listings in place and in order?', max_length=255, null=True)),
                ('yes_5', models.BooleanField(default=False)),
                ('no_5', models.BooleanField(default=False)),
                ('quest_head_6', models.CharField(blank=True, default='Does business have a consolidated conversation stream? Is it mobile-friendly?', max_length=255, null=True)),
                ('yes_6', models.BooleanField(default=False)),
                ('no_6', models.BooleanField(default=False)),
                ('quest_head_7', models.CharField(blank=True, default='Is business leveraging Text Snippets or auto-replies for FAQs?', max_length=255, null=True)),
                ('yes_7', models.BooleanField(default=False)),
                ('no_7', models.BooleanField(default=False)),
                ('quest_head_8', models.CharField(blank=True, default='Is the business set up to send personalized video messages to leads?', max_length=255, null=True)),
                ('yes_8', models.BooleanField(default=False)),
                ('no_8', models.BooleanField(default=False)),
                ('quest_head_9', models.CharField(blank=True, default='Does the business have Tap-2-Pay?', max_length=255, null=True)),
                ('yes_9', models.BooleanField(default=False)),
                ('no_9', models.BooleanField(default=False)),
                ('quest_head_10', models.CharField(blank=True, default='Tap to pay turns smartphones into credit card readers, enabling payment anywhere', max_length=255, null=True)),
                ('yes_10', models.BooleanField(default=False)),
                ('no_10', models.BooleanField(default=False)),
                ('quest_head_11', models.CharField(blank=True, default='Does business have an acceptable rating?', max_length=255, null=True)),
                ('yes_11', models.BooleanField(default=False)),
                ('no_11', models.BooleanField(default=False)),
                ('quest_head_12', models.CharField(blank=True, default='Are reviews being generated frequently and consistently?', max_length=255, null=True)),
                ('yes_12', models.BooleanField(default=False)),
                ('no_12', models.BooleanField(default=False)),
                ('quest_head_13', models.CharField(blank=True, default='Are reviews being replied to?', max_length=255, null=True)),
                ('yes_13', models.BooleanField(default=False)),
                ('no_13', models.BooleanField(default=False)),
                ('quest_head_14', models.CharField(blank=True, default='Does business have a database of emails and phone numbers?', max_length=255, null=True)),
                ('yes_14', models.BooleanField(default=False)),
                ('no_14', models.BooleanField(default=False)),
                ('quest_head_15', models.CharField(blank=True, default='Does business have a way to send bulk email/sms?', max_length=255, null=True)),
                ('yes_15', models.BooleanField(default=False)),
                ('no_15', models.BooleanField(default=False)),
                ('quest_head_16', models.CharField(blank=True, default='Does business have a Newsletter Builder?', max_length=255, null=True)),
                ('yes_16', models.BooleanField(default=False)),
                ('no_16', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='testimonial')),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='profiles')),
                ('business_logo', models.FileField(blank=True, null=True, upload_to='logos')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('whats_app_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('insta', models.CharField(blank=True, max_length=500, null=True)),
                ('twitter', models.CharField(blank=True, max_length=500, null=True)),
                ('facebook', models.CharField(blank=True, max_length=500, null=True)),
                ('youtube', models.CharField(blank=True, max_length=500, null=True)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=255, null=True)),
                ('stablish_year', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=500, null=True)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('business_segment', models.CharField(blank=True, max_length=255, null=True)),
                ('business_description', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('service_area', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=None)),
                ('business_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=None)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_quill.fields.QuillField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='thumbnail')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
