# Generated by Django 4.2.4 on 2023-09-03 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('whats_app_number', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('insta', models.TextField()),
                ('twitter', models.TextField()),
                ('facebook', models.TextField()),
                ('youtube', models.TextField()),
                ('business_name', models.CharField(max_length=255)),
                ('gst_number', models.CharField(max_length=255)),
                ('stablish_year', models.CharField(max_length=255)),
                ('website', models.TextField()),
                ('tagline', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=255)),
                ('business_description', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
