# Generated by Django 4.1.2 on 2023-09-04 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sky_app', '0002_skycard_business_logo_skycard_profile_imge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skycard',
            old_name='profile_imge',
            new_name='profile_image',
        ),
    ]
