# Generated by Django 4.1.2 on 2023-09-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_app', '0003_rename_profile_imge_skycard_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skycard',
            name='business_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='skycard',
            name='facebook',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='skycard',
            name='insta',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='skycard',
            name='twitter',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='skycard',
            name='website',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='skycard',
            name='youtube',
            field=models.CharField(max_length=500),
        ),
    ]
