# Generated by Django 4.2.4 on 2023-09-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_app', '0006_alter_skycard_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skycard',
            name='business_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
