# Generated by Django 4.1.2 on 2023-09-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_app', '0008_metatags_testimonial_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='creaded_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
