# Generated by Django 4.2.4 on 2023-09-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sky_app', '0012_blog_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='creaded_by',
            new_name='created_by',
        ),
    ]
