# Generated by Django 4.2.4 on 2023-09-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_app', '0014_sureveyquest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sureveyquest',
            name='no_10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='no_11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='no_12',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='no_13',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='no_14',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='no_15',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='no_16',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='no_17',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='no_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='no_8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='no_9',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='quest_head_10',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='quest_head_11',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='quest_head_12',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='quest_head_13',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='quest_head_14',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='quest_head_15',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='quest_head_16',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='quest_head_17',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='quest_head_7',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='quest_head_8',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='quest_head_9',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='yes_10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='yes_11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='yes_12',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='yes_13',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='yes_14',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='yes_15',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='yes_16',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='yes_17',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='yes_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='yes_8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='yes_9',
            field=models.BooleanField(default=False),
        ),
    ]
