# Generated by Django 4.2.4 on 2023-09-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_app', '0016_alter_sureveyquest_quest_head_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sureveyquest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sureveyquest',
            name='total_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sureveyquest',
            name='quest_head_10',
            field=models.CharField(blank=True, default='Tap to pay turns smartphones into credit card readers, enabling payment anywhere', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sureveyquest',
            name='quest_head_11',
            field=models.CharField(blank=True, default='Does business have an acceptable rating?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sureveyquest',
            name='quest_head_12',
            field=models.CharField(blank=True, default='Are reviews being generated frequently and consistently?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sureveyquest',
            name='quest_head_13',
            field=models.CharField(blank=True, default='Are reviews being replied to?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sureveyquest',
            name='quest_head_14',
            field=models.CharField(blank=True, default='Does business have a database of emails and phone numbers?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sureveyquest',
            name='quest_head_15',
            field=models.CharField(blank=True, default='Does business have a way to send bulk email/sms?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sureveyquest',
            name='quest_head_17',
            field=models.CharField(blank=True, default='Does business have a Newsletter Builder?', max_length=255, null=True),
        ),
    ]
