# Generated by Django 4.2.4 on 2023-09-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_app', '0017_sureveyquest_email_sureveyquest_total_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sureveyquest',
            name='no_17',
        ),
        migrations.RemoveField(
            model_name='sureveyquest',
            name='quest_head_17',
        ),
        migrations.RemoveField(
            model_name='sureveyquest',
            name='yes_17',
        ),
        migrations.AlterField(
            model_name='sureveyquest',
            name='quest_head_16',
            field=models.CharField(blank=True, default='Does business have a Newsletter Builder?', max_length=255, null=True),
        ),
    ]
