# Generated by Django 4.2.4 on 2023-09-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_app', '0018_remove_sureveyquest_no_17_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sureveyquest',
            name='solution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
