# Generated by Django 4.2.4 on 2023-09-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_app', '0019_sureveyquest_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sureveyquest',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
