# Generated by Django 4.2.4 on 2023-09-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_app', '0021_alter_sureveyquest_quest_head_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sureveyquest',
            name='quest_head_2',
            field=models.CharField(blank=True, default='Does website have a text-enabled phone number?', max_length=255, null=True),
        ),
    ]
