# Generated by Django 4.2.4 on 2023-10-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_app', '0022_alter_sureveyquest_quest_head_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sureveyquest',
            name='quest_head_9',
            field=models.CharField(blank=True, default='Does the business have Tap-2-Pay?', max_length=255, null=True),
        ),
    ]
