# Generated by Django 4.2.4 on 2023-10-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_app', '0023_alter_sureveyquest_quest_head_9'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=40)),
                ('website', models.URLField()),
            ],
        ),
    ]
