# Generated by Django 4.2.4 on 2023-10-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_app', '0024_partnerus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerus',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partnerus',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='partnerus',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
