# Generated by Django 4.2.4 on 2023-10-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_app', '0026_newslettersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('services', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
